[config]
path = "../data/datacollection_mini/Sim2RealFoundationPolicy/"
path_exorl_learn = "../data/datacollection_mini/exorl_learn/"
path_exorl_learn_44 = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2024.12.17/034327_rnd/verify/"
path_exorl_learn_44_true = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.01.16/formal_44_demo"
path_exorl_learn_24_true = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.01.16/formal_24_demo"
path_exorl_learn_mixed_true = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.01.16/formal_mixed_demo"
path_exorl_learn_24_true_RMSPROP = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.04.01/better_24_demo"
path_exorl_learn_earth_aligned = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.04.10/align_earth_demo"
path_exorl_learn_24_aligned = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.04.10/align_24_demo"
path_exorl_learn_24_aligned_s_a = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.04.24/align_24_s_a"
path_exorl_learn_earth_aligned_s_a = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.04.24/alin_earth_s_a"
path_exorl_learn_15_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.05.13/align_15"
path_exorl_learn_24_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.05.13/align_24"
path_exorl_learn_34_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.05.13/align_34"
path_exorl_learn_44_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.05.13/align_44"
path_exorl_learn_fri_4_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.06.05/fri_4"
path_exorl_learn_fri_5_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.06.05/fri_5"
path_exorl_learn_fri_6_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.06.05/fri_6"
path_exorl_learn_fri_7_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.06.05/fri_7"
path_exorl_learn_fri_8_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.06.05/fri_8"
path_exorl_learn_fri_18_aligned_dlc = "../data/datacollection_mini/url_verify_solved/url_benchmark/exp_local/2025.06.05/fri_18"
